name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  # unit tests
  units:
    runs-on:
      - self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.0
        with:
          node-version: "12"
      - run: npm ci
      - run: npm test

  # test action works running from the graph
  test:
    runs-on:
      - self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: airnity/docker-build-push-action@main
        with:
          image-name: test
          image-tag: v1.0.0
          dockerfile-path: ./.tests/Dockerfile
      - uses: ./
        with:
          image-name: test2
          image-tag: v1.0.0
          original-name: test:v1.0.0
